--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    secondary_emails jsonb not null default '[]'::jsonb,
    constraint sales_secondary_emails_is_array check (jsonb_typeof(secondary_emails) = 'array')
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);

-- SnowEnduro CRM domain tables
create table public.website_leads (
    id uuid primary key default gen_random_uuid(),
    public_code bigint generated always as identity unique,
    created_at timestamp with time zone not null default now(),
    customer_name text not null check (char_length(customer_name) between 2 and 100),
    phone text not null check (char_length(phone) between 7 and 32),
    product_interest text not null check (char_length(product_interest) between 2 and 200),
    source_page text not null check (char_length(source_page) between 1 and 600),
    compatibility_make text,
    compatibility_model text,
    compatibility_year integer check (compatibility_year is null or compatibility_year between 1950 and 2100),
    manager_comments text not null default '' check (char_length(manager_comments) <= 5000),
    status text not null default 'new' check (status in ('new', 'in_progress', 'supplier', 'sale', 'rejected')),
    idempotency_key uuid not null unique,
    consent_at timestamp with time zone not null,
    consent_policy_version text not null check (char_length(consent_policy_version) between 1 and 80)
);
create index website_leads_created_at_idx on public.website_leads using btree (created_at desc);
create index website_leads_status_created_at_idx on public.website_leads using btree (status, created_at desc);

create table public.products (
    id uuid primary key default gen_random_uuid(),
    slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' and char_length(slug) <= 120),
    category text not null check (category in ('snowbike', 'snowmobile')),
    name text not null check (char_length(name) between 1 and 160),
    data jsonb not null check (jsonb_typeof(data) = 'object'),
    availability text not null default 'on_order' check (availability in ('in_stock', 'on_order', 'out_of_stock')),
    is_published boolean not null default false,
    sort_order integer not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
create index products_catalog_order_idx on public.products using btree (is_published, sort_order, name);

create table public.telegram_recipients (
    id uuid primary key default gen_random_uuid(),
    chat_id text not null unique check (chat_id ~ '^-?[0-9]{1,20}$'),
    label text,
    is_enabled boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create table public.notification_outbox (
    id uuid primary key default gen_random_uuid(),
    lead_id uuid not null references public.website_leads(id) on delete cascade,
    created_at timestamp with time zone not null default now(),
    state text not null default 'pending' check (state in ('pending', 'sent', 'failed')),
    attempt_count integer not null default 0 check (attempt_count >= 0),
    last_error text,
    sent_at timestamp with time zone,
    unique (lead_id)
);
create index notification_outbox_state_created_idx on public.notification_outbox using btree (state, created_at);

create table public.catalog_publication_jobs (
    id uuid primary key default gen_random_uuid(),
    requested_by uuid references auth.users(id) on delete set null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    status text not null default 'queued' check (status in ('queued', 'running', 'succeeded', 'failed')),
    expires_at timestamp with time zone not null,
    error_message text
);
create index catalog_publication_jobs_created_idx on public.catalog_publication_jobs using btree (created_at desc);

create table public.website_lead_rate_limits (
    subject_hash text not null check (subject_hash ~ '^[a-f0-9]{64}$'),
    bucket text not null check (bucket in ('ip', 'phone')),
    window_start timestamp with time zone not null default now(),
    request_count integer not null default 0 check (request_count >= 0),
    primary key (subject_hash, bucket)
);

create table public.notification_deliveries (
    id uuid primary key default gen_random_uuid(),
    outbox_id uuid not null references public.notification_outbox(id) on delete cascade,
    recipient_id uuid not null references public.telegram_recipients(id) on delete cascade,
    state text not null default 'pending' check (state in ('pending', 'sent', 'failed')),
    attempt_count integer not null default 0 check (attempt_count >= 0),
    last_error text,
    sent_at timestamp with time zone,
    updated_at timestamp with time zone not null default now(),
    unique (outbox_id, recipient_id)
);
create index notification_deliveries_state_idx on public.notification_deliveries using btree (outbox_id, state);
